// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOs5X5g8-rIkVKtQ4MqJP_DT1LHaGIrNY',
    appId: '1:186218929331:web:bfc8236e811b4402cae4c6',
    messagingSenderId: '186218929331',
    projectId: 'rojgar-kendra-b2fb8',
    authDomain: 'rojgar-kendra-b2fb8.firebaseapp.com',
    storageBucket: 'rojgar-kendra-b2fb8.firebasestorage.app',
    measurementId: 'G-5MRRJ9VQV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaH9ZLjNeGzEjJRE6zbknutOowt1xmOA',
    appId: '1:186218929331:android:d2b9e01686405ea4cae4c6',
    messagingSenderId: '186218929331',
    projectId: 'rojgar-kendra-b2fb8',
    storageBucket: 'rojgar-kendra-b2fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4DNguWaLO6awPAvufIxFCIwZKd2-3Ssc',
    appId: '1:186218929331:ios:a80506782309a82fcae4c6',
    messagingSenderId: '186218929331',
    projectId: 'rojgar-kendra-b2fb8',
    storageBucket: 'rojgar-kendra-b2fb8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4DNguWaLO6awPAvufIxFCIwZKd2-3Ssc',
    appId: '1:186218929331:ios:a80506782309a82fcae4c6',
    messagingSenderId: '186218929331',
    projectId: 'rojgar-kendra-b2fb8',
    storageBucket: 'rojgar-kendra-b2fb8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOs5X5g8-rIkVKtQ4MqJP_DT1LHaGIrNY',
    appId: '1:186218929331:web:609d999066ee4d97cae4c6',
    messagingSenderId: '186218929331',
    projectId: 'rojgar-kendra-b2fb8',
    authDomain: 'rojgar-kendra-b2fb8.firebaseapp.com',
    storageBucket: 'rojgar-kendra-b2fb8.firebasestorage.app',
    measurementId: 'G-XGS0F29T24',
  );
}
